三个内容更新
pattazl/markdown-image-manage pull request #3
Opened 2023-05-22 04:09 UTC by shaolonger

主要提交内容：
1、修复vscode语言未在默认值内时插件异常报错的问题
2、递归创建图片文件夹，以此保证中间目录不存在时不会异常
3、剔除不合法字符后，若已丢失拓展名，则自动根据文件buffer内容补充

2023-06-20 22:29 UTC, pattazl commented
谢谢，我周末抽空合并下。

2023-06-22 14:59 UTC, pattazl approved these changes

2023-06-22 15:00 UTC, pattazl requested changes
已经有 fs-extra库，可以直接用 
import * as fsExt from "fs-extra";
 fsExt.ensureDirSync(dest);

2023-06-22 15:04 UTC, pattazl approved these changes

2023-06-22 15:05 UTC, pattazl approved these changes

2023-06-22 15:06 UTC, pattazl approved these changes

2023-06-22 15:09 UTC, pattazl commented
有空帮忙把递归文件夹的代码用 fs-extra 的函数替代下，然后我就合并发布下，谢谢支持。

2023-06-25 02:42 UTC, shaolonger commented
> 有空帮忙把递归文件夹的代码用 fs-extra 的函数替代下，然后我就合并发布下，谢谢支持。

已经改好更新了:)

2023-06-25 12:03 UTC, pattazl approved these changes

2023-06-25 12:04 UTC, merged

2023-06-25 13:23 UTC, pattazl commented
已经完成合并，并发布为 0.1.1